/**
 * Fetch latest NBS Nigeria CPI (via World Bank / IMF) and regenerate
 * scripts/raw-cpi-data.csv for build:cpi.
 *
 * Usage: npx tsx scripts/fetch-live-cpi.ts
 * Then:  npm run build:cpi
 *
 * 2009-2025 come from the World Bank indicator FP.CPI.TOTL (2010=100 base,
 * NBS-linked), rescaled onto the app's continuous 2009=100 base.
 * The current year (no published value yet) keeps the existing projection
 * from lib/cpi.data.json, or falls back to a growth assumption.
 */

import * as fs from "fs";
import * as path from "path";

const WORLD_BANK_URL =
  "https://api.worldbank.org/v2/country/NGA/indicator/FP.CPI.TOTL?format=json&date=2009:2030&per_page=100";
const CURRENT_YEAR = new Date().getFullYear();
const CURRENT_YEAR_GROWTH_ASSUMPTION = 0.16;

async function fetchWorldBankCPI(): Promise<Map<number, number>> {
  const res = await fetch(WORLD_BANK_URL);
  if (!res.ok) throw new Error(`World Bank request failed: HTTP ${res.status}`);
  const json = await res.json();
  const rows: { date: string; value: number | null }[] = Array.isArray(json)
    ? json[1]
    : null;
  if (!Array.isArray(rows) || rows.length === 0) {
    throw new Error("World Bank returned no data");
  }
  const map = new Map<number, number>();
  for (const row of rows) {
    if (row.value != null) map.set(Number(row.date), Number(row.value));
  }
  return map;
}

function readExistingBundled(): Map<number, number> {
  const existingPath = path.join(__dirname, "..", "lib", "cpi.data.json");
  try {
    const existing = JSON.parse(
      fs.readFileSync(existingPath, "utf-8")
    ) as { data: { year: number; cpi: number }[] };
    return new Map(existing.data.map((d) => [d.year, d.cpi]));
  } catch {
    return new Map();
  }
}

function rescaleToAppBase(
  live: Map<number, number>,
  bundled: Map<number, number>
): number {
  const overlaps: number[] = [];
  live.forEach((value, year) => {
    const b = bundled.get(year);
    if (b !== undefined) overlaps.push(b / value);
  });
  if (overlaps.length === 0) {
    // Fall back to the 2009 average anchor (bundled 2009 = 100)
    const b2009 = bundled.get(2009);
    const l2009 = live.get(2009);
    if (b2009 === undefined || l2009 === undefined) return 1;
    return b2009 / l2009;
  }
  return overlaps.reduce((a, b) => a + b, 0) / overlaps.length;
}

function main() {
  const bundled = readExistingBundled();
  const years: { year: number; cpi: number }[] = [];

  let lastCompleted: number | undefined;

  fetchWorldBankCPI()
    .then((live) => {
      const scale = rescaleToAppBase(live, bundled);
      const completedYears = Array.from(live.keys()).sort((a, b) => a - b);

      for (const year of completedYears) {
        years.push({ year, cpi: Math.round(live.get(year)! * scale * 10) / 10 });
        lastCompleted = year;
      }

      const existing = bundled.get(CURRENT_YEAR);
      let projection: number;
      if (existing !== undefined) {
        projection = existing;
      } else if (lastCompleted !== undefined) {
        projection =
          Math.round(
            years.find((y) => y.year === lastCompleted)!.cpi *
              (1 + CURRENT_YEAR_GROWTH_ASSUMPTION) *
              10
          ) / 10;
      } else {
        throw new Error("Cannot project current year: no base data");
      }
      years.push({ year: CURRENT_YEAR, cpi: projection });

      const lines = [
        "# NBS Nigeria Composite CPI — annual average (Nov 2009 = 100)",
        "# Generated by scripts/fetch-live-cpi.ts from World Bank / IMF data.",
        `# ${CURRENT_YEAR} is a projection (current-year estimate).`,
        "year,cpi",
        ...years
          .sort((a, b) => a.year - b.year)
          .map((y) => `${y.year},${y.cpi}`),
      ];

      const csvPath = path.join(__dirname, "raw-cpi-data.csv");
      fs.writeFileSync(csvPath, lines.join("\n") + "\n");
      console.log(`✅ Wrote ${years.length} CPI rows to ${csvPath}`);
      console.log(`   Years: ${years[0].year} – ${CURRENT_YEAR} (${CURRENT_YEAR} projected)`);
      console.log(`   Next step: npm run build:cpi`);
    })
    .catch((err) => {
      console.error("❌ Error fetching live CPI data:", err);
      process.exit(1);
    });
}

main();
